package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1

import it.unisalento.business.ClienteBusiness;
import it.unisalento.dao.AffittoDao;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 * Affitto generated by hbm2java
 */
public class Affitto 
{
	private int idAffitto;
	private int operatorelido;
	private int cabina;
	private GregorianCalendar dataInizio;
	private GregorianCalendar dataFine;
	private String acquaCorrente;
	private String elettricità;
	private String asciugamani;
	private Cliente cliente;
	private int IdCliente;
	private double costo;
	
	

	public Affitto()
	{
	}
	
	

	public Affitto(int idAffitto) {
		this.idAffitto = idAffitto;
	}



	public Affitto(int operatorelido, int cabina, Cliente cliente)
	{
		this.operatorelido = operatorelido;
		this.cabina = cabina;
		this.cliente = cliente;
	}

	public Affitto(GregorianCalendar dataInizio, GregorianCalendar dataFine)
{
	
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		
	}
	
	
	

	public Affitto(GregorianCalendar dataInizio, GregorianCalendar dataFine,
			int idCliente) {
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		IdCliente = idCliente;
	}



	public Affitto(int idAffitto, int operatorelido, int cabina,
			GregorianCalendar inizio,GregorianCalendar fine,
			String acquaCorrente, String elettricità, String asciugamani,
			int idCliente, double costo) 
	{
		this.idAffitto = idAffitto;
		this.operatorelido = operatorelido;
		this.cabina = cabina;
		this.acquaCorrente = acquaCorrente;
		this.elettricità = elettricità;
		this.asciugamani = asciugamani;
		this.IdCliente = idCliente;
		this.costo = costo;
		this.dataInizio = inizio;
		this.dataFine = fine;
	}

	public Integer getIdAffitto() {
		return this.idAffitto;
	}

	public void setIdAffitto(Integer idAffitto) {
		this.idAffitto = idAffitto;
	}

	public int getOperatorelido() {
		return this.operatorelido;
	}

	public void setOperatorelido(int operatorelido) {
		this.operatorelido = operatorelido;
	}

	public int getCabina() {
		return this.cabina;
	}

	public void setCabina(int cabina) {
		this.cabina = cabina;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public GregorianCalendar getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(GregorianCalendar dataInizio) {
		this.dataInizio = dataInizio;
	}

	public GregorianCalendar getDataFine() {
		return this.dataFine;
	}

	public void setDataFine(GregorianCalendar dataFine) {
		this.dataFine = dataFine;
	}

	public String getAcquaCorrente() {
		return this.acquaCorrente;
	}

	public void setAcquaCorrente(String acquaCorrente) {
		this.acquaCorrente = acquaCorrente;
	}

	public String getElettricità() {
		return this.elettricità;
	}

	public void setElettricità(String elettricità) {
		this.elettricità = elettricità;
	}

	public String getAsciugamani() {
		return this.asciugamani;
	}

	public void setAsciugamani(String asciugamani) {
		this.asciugamani = asciugamani;
	}
	
	
	

	public int getIdCliente() {
		return IdCliente;
	}

	public void setIdCliente(int idCliente) {
		IdCliente = idCliente;
	}

	public double getCosto() {
		return costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	public void setIdAffitto(int idAffitto) {
		this.idAffitto = idAffitto;
	}

	public int getMaxId()
	{
		return AffittoDao.getInstance().affittoMaxId();
	}

	public String toString()
	{
		cliente = ClienteBusiness.getInstance().trovaCliente(IdCliente);
		int annoInizio = dataInizio.get(Calendar.YEAR);
		int meseInizio = dataInizio.get(Calendar.MONTH)+1;
		int giornoInizio = dataInizio.get(Calendar.DATE);
		
		int annoFine = dataFine.get(Calendar.YEAR);
		int meseFine = dataFine.get(Calendar.MONTH)+1;
		int giornoFine = dataFine.get(Calendar.DATE);
		
		String affitto ="Affitto num. :"+this.getIdAffitto()+"  Cod. Op. :"+this.getOperatorelido()+
				"   Cliente :"+this.cliente.getCognome()+" "+this.cliente.getNome()+"  Data Inizio :"+giornoInizio+"-"+
						meseInizio+"-"+annoInizio+"  Data Fine :"+giornoFine+"-"+
								meseFine+"-"+annoFine+"  Codice Cabina:"+this.getCabina()+"  Acqua Corrente :"+this.getAcquaCorrente()+
				"  Elettricita :"+this.getElettricità()+"  Servizio Asciugamani :"+this.getAsciugamani()+"   Costo totale : euro "+this.getCosto();
		
		return(affitto);
				}


	public Affitto recupera()
	{
		return(AffittoDao.getInstance().getAffitto(this));
	}

	public boolean registra()
	{
		
		return(AffittoDao.getInstance().inserisciAffitto(this));
	}
	
	public boolean deleteAffitto()
	{
		return AffittoDao.getInstance().cancellaAffitto(this);
	}
	
	
}



