package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1



import it.unisalento.dao.AmministratoreDao;

/**
 * Amministratore generated by hbm2java
 */
public class Amministratore extends Operatorelido  {

	private int codiceAmministratore;
	private String mansione;
	
	public Amministratore() 
	{
		
	}
	public Amministratore (int codice)
	{
		super(codice);
		
	}
	
	
	public Amministratore (int codice,String psw)
	{
		super(codice,psw);
		
	}

	public Amministratore(int codice,String nome,String cognome,String password,String mansione)
	{
		super(codice,nome,cognome,password);
		this.mansione = mansione;
		
	}

	public int getCodiceAmministratore() {
		return this.codiceAmministratore;
	}

	public void setCodiceAmministratore(int codiceAmministratore) {
		this.codiceAmministratore = codiceAmministratore;
	}

	public String getMansione() {
		return this.mansione;
	}

	public void setMansione(String mansione) {
		this.mansione = mansione;
	}

	
		
	public boolean login()
	{
		return AmministratoreDao.getInstance().userExists(this);
	}

}
