package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1



/**
 * Cabina generated by hbm2java
 */
public class Cabina 
{

	private int idCabina;
	private Dimensione dimensione;
	private boolean prenotato;
	private boolean occupato;
	private double costoServizioAggiuntivo;
	
	

	public Cabina() 
	{
	}
	
	
	
	public Cabina(int idCabina) {
		this.idCabina = idCabina;
	}



	public Cabina(int idCabina,boolean prenotato)
	{
		this.idCabina = idCabina;
		this.prenotato = prenotato;
	}



	public Cabina(boolean prenotato,
			boolean occupato, double costoServizioAggiuntivo) {
		
		this.prenotato = prenotato;
		this.occupato = occupato;
		this.costoServizioAggiuntivo = costoServizioAggiuntivo;
	}


	public Cabina(Dimensione dimensione, boolean prenotato,
			boolean occupato, double costoServizioAggiuntivo) {
		this.dimensione = dimensione;
		this.prenotato = prenotato;
		this.occupato = occupato;
		this.costoServizioAggiuntivo = costoServizioAggiuntivo;
	}

	
	public int getIdCabina() {
		return this.idCabina;
	}

	public void setIdCabina(int idCabina) {
		this.idCabina = idCabina;
	}

	public Dimensione getDimensione() {
		return this.dimensione;
	}

	public void setDimensione(Dimensione dimensione) {
		this.dimensione = dimensione;
	}

	public boolean isPrenotato() {
		return this.prenotato;
	}

	public void setPrenotato(boolean prenotato) {
		this.prenotato = prenotato;
	}

	public boolean isOccupato() {
		return this.occupato;
	}

	public void setOccupato(boolean occupato) {
		this.occupato = occupato;
	}

	public double getCostoServizioAggiuntivo() {
		return this.costoServizioAggiuntivo;
	}

	public void setCostoServizioAggiuntivo(double costoServizioAggiuntivo) {
		this.costoServizioAggiuntivo = costoServizioAggiuntivo;
	}

}
