package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1


import it.unisalento.dao.ClienteDao;
import java.util.Calendar;
import java.util.GregorianCalendar;



/**
 * Cliente generated by hbm2java
 */
public class Cliente 
{

	private int idCliente;
	private int operatorelido;
	private String nome;
	private String cognome;
	private int età;
	private char sesso;
	private String email;
	private String password;
	private GregorianCalendar dataRegistrazione;
	
	

	public Cliente() 
	{
		
	}
	
	public Cliente(int codice)
	{
		
		this.idCliente = codice;
	}
		public Cliente(int codice , String password) 
		{
			
			this.idCliente = codice;
			this.password = password;
			
		}
	

	public Cliente(String nome, String cognome, String password) 
	{
		
		this.nome = nome;
		this.cognome = cognome;
		this.password = password;
		
	}

	public Cliente(int idCliente, String nome, String cognome,String password,
			int età, char sesso, String email) 
	{
		this.idCliente = idCliente;
		this.nome = nome;
		this.cognome = cognome;
		this.età = età;
		this.sesso = sesso;
		this.email = email;
		this.password = password;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public int getOperatorelido() {
		return this.operatorelido;
	}

	public void setOperatorelido(int operatorelido) {
		this.operatorelido = operatorelido;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public Integer getEtà() {
		return this.età;
	}

	public void setEtà(Integer età) {
		this.età = età;
	}

	public char getSesso() {
		return this.sesso;
	}

	public void setSesso(char sesso) {
		this.sesso = sesso;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public GregorianCalendar getDataRegistrazione() {
		return this.dataRegistrazione;
	}

	public void setDataRegistrazione(GregorianCalendar dataRegistrazione) {
		this.dataRegistrazione = dataRegistrazione;
	}

	
	
	public boolean login()
	{
		return ClienteDao.getInstance().userExists(this);
	}

	public boolean verifica()
	{
		return ClienteDao.getInstance().usernameExists(this);
	}
/**
 * Registrazione on Line del Cliente.Il codice Operatore
 * viene inserito dal sistema(num : 0).
 * La data inserita è quella odierna.
 * @return true  sempre...
 */
	
	public boolean registra()
	{
		
		return(ClienteDao.getInstance().inserisciCliente(this));
	}
	

	
	public Cliente recupera()
	{
		return(ClienteDao.getInstance().getCliente(this));
	}
	
	/**
	 * Sovrascrive toString di Object.
	 * 
	 * @return cliente  la stringa formattata
	 * 
	 */
	public String toString()
	{
		int anno = dataRegistrazione.get(Calendar.YEAR);
		int mese = dataRegistrazione.get(Calendar.MONTH)+1;
		int giorno = dataRegistrazione.get(Calendar.DATE);
		int operatore = this.getOperatorelido();
		String op;
		if(operatore == 0)
		{
			op = "  Registrazione onLine ";
		}
		else 
		{
		    op = "  Registrazione da operatore";
		}
		String cliente ="Cliente num. :"+this.getIdCliente()+"(=username)  Nome :"+this.getNome()+
				"   Cognome :"+this.getCognome()+"   Sesso :"+sesso+"  Email:"+email+"  Data Registrazione :"+giorno+"-"+
				mese+"-"+anno+"   Password :"+password+" "+op;
		return(cliente);
				}

}
