package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1


/**
 * Dimensione generated by hbm2java
 */
public class Dimensione 
 {

	private String tipo;
	private double costogiornaliero;
	
	public Dimensione() 
	{
	}

	public Dimensione(String tipo) {
		this.tipo = tipo;
	}

	public Dimensione(String tipo, double costogiornaliero)
	{
		this.tipo = tipo;
		this.costogiornaliero = costogiornaliero;
		
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public double getCostogiornaliero() 
	{
		return this.costogiornaliero;
	}

	public void setCostogiornaliero(double costogiornaliero) {
		this.costogiornaliero = costogiornaliero;
	}

	

}
