package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1


/**
 * Lettino generated by hbm2java
 */
public class Lettino 
{

	private int idLettino;
	public  static final double COSTO_GIORNALIERO = 4.00;
	private boolean occupato;

	public Lettino() 
	{
	}

	

	public Integer getIdLettino() {
		return this.idLettino;
	}

	public void setIdLettino(Integer idLettino) {
		this.idLettino = idLettino;
	}

		
	public boolean isOccupato() {
		return this.occupato;
	}

	public void setOccupato(boolean occupato) {
		this.occupato = occupato;
	}

}
