package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1


/**
 * Ombrellone generated by hbm2java
 */
public class Ombrellone 
 {

	private int idOmbrellone;
	private double costoGiornaliero;
	private boolean occupato;
	//private Lettino[] lettini = new Lettino[2];

	public Ombrellone() 
	{
	}
     
	public Ombrellone(int codice,boolean occupato)
	{
		this.idOmbrellone = codice;
		this.occupato = occupato;
		
	}
	
	public Ombrellone(int codice,double costo,boolean occupato)
	{
		this.idOmbrellone = codice;
		this.occupato = occupato;
		this.costoGiornaliero = costo;
		
	}
	
	public Ombrellone(double costoGiornaliero) 
	{
		this.costoGiornaliero = costoGiornaliero;
		
	}

	public Integer getIdOmbrellone() {
		return this.idOmbrellone;
	}

	public void setIdOmbrellone(Integer idOmbrellone) {
		this.idOmbrellone = idOmbrellone;
	}

	public double getCostoGiornaliero() {
		return this.costoGiornaliero;
	}

	public void setCostoGiornaliero(double costoGiornaliero) {
		this.costoGiornaliero = costoGiornaliero;
	}

	public boolean isOccupato() {
		return this.occupato;
	}

	public void setOccupato(boolean occupato) {
		this.occupato = occupato;
	}

	/*public Lettino[]  getLettinos() {
		return this.lettini;
	}

	public void setLettini(Lettino[] lettini) {
		this.lettini = lettini;
	}
	*/
	


}
