package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1


/**
 * Operatorelido generated by hbm2java
 */
public class Operatorelido 
{

	private int codiceOperatore;
	private String nome;
	private String cognome;
	private String password;
	
	
	public Operatorelido() 
	{
		
		
	}
	public Operatorelido(int codice)
	{
		this.codiceOperatore = codice;
		
	}

	public Operatorelido(int codice,String password) 
	{
		
		this.password = password;
		this.codiceOperatore = codice;
	}

	public Operatorelido(int codice,String nome, String cognome, String password)
	{
		this.codiceOperatore = codice;
		this.nome = nome;
		this.cognome = cognome;
		this.password = password;
	}
	
	
	
	public Operatorelido(String nome, String cognome, String password) 
	{
		this.nome = nome;
		this.cognome = cognome;
		this.password = password;
		
	}

	public int getCodiceOperatore() {
		return this.codiceOperatore;
	}

	public void setCodiceOperatore(int codiceOperatore) {
		this.codiceOperatore = codiceOperatore;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}


	

}
