package it.unisalento.model;
// Generated 24-gen-2014 21.43.37 by Hibernate Tools 3.4.0.CR1

import it.unisalento.business.ClienteBusiness;
import it.unisalento.dao.PrenotazioneDao;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 * Prenotazione generated by hbm2java
 */
public class Prenotazione 
{

	private int idPrenotazione;
	private int cabina;
	private Cliente cliente;
	private GregorianCalendar dataInizio;
	private GregorianCalendar dataFine;
	private String elettricità;
	private String acquaCorrente;
	private String asciugamani;
	private boolean confermato;
	private int IdCliente;
	private double costo;

	public Prenotazione() 
	{
	}
	
	

	public Prenotazione(int idPrenotazione) {
		this.idPrenotazione = idPrenotazione;
	}



	public Prenotazione(int cabina, Cliente cliente,GregorianCalendar dataInizio,
			GregorianCalendar dataFine) 
	{
		this.cabina = cabina;
		this.cliente = cliente;
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		this.confermato = false;
	}
	
	

	public Prenotazione(int idPrenotazione, int cabina, int idCliente,
			GregorianCalendar dataInizio, GregorianCalendar dataFine,
			String elettricità, String acquaCorrente, String asciugamani,
			double costo) {
		this.idPrenotazione = idPrenotazione;
		this.cabina = cabina;
		IdCliente = idCliente;
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		this.elettricità = elettricità;
		this.acquaCorrente = acquaCorrente;
		this.asciugamani = asciugamani;
		this.costo = costo;
	}



	public Prenotazione(int idPrenotazione,int cabina, int Idcliente, GregorianCalendar dataInizio,
			GregorianCalendar dataFine, String elettricità, String acquaCorrente,
			String asciugamani,boolean confermato,double costo) {
		this.cabina = cabina;
		this.IdCliente = Idcliente;
		this.dataInizio = dataInizio;
		this.dataFine = dataFine;
		this.elettricità = elettricità;
		this.acquaCorrente = acquaCorrente;
		this.asciugamani = asciugamani;
		this.confermato = confermato;
		this.idPrenotazione = idPrenotazione;
		this.costo = costo;
	}
	
	

	public Integer getIdPrenotazione() {
		return this.idPrenotazione;
	}

	public int getCabina() {
		return this.cabina;
	}

	public void setCabina(int cabina) {
		this.cabina = cabina;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public GregorianCalendar getDataInizio() {
		return this.dataInizio;
	}

	public void setDataInizio(GregorianCalendar dataInizio) {
		this.dataInizio = dataInizio;
	}

	public GregorianCalendar getDataFine() {
		return this.dataFine;
	}

	public void setDataFine(GregorianCalendar dataFine) {
		this.dataFine = dataFine;
	}

	public String getElettricità() {
		return this.elettricità;
	}

	public void setElettricità(String elettricità) {
		this.elettricità = elettricità;
	}

	public String getAcquaCorrente() {
		return this.acquaCorrente;
	}

	public void setAcquaCorrente(String acquaCorrente) {
		this.acquaCorrente = acquaCorrente;
	}

	public String getAsciugamani() {
		return this.asciugamani;
	}

	public void setAsciugamani(String asciugamani) {
		this.asciugamani = asciugamani;
	}

	public boolean isConfermato() {
		return this.confermato;
	}

	public void setConfermato(boolean confermato) {
		this.confermato = confermato;
	}
	
	public int getIdCliente() {
		return IdCliente;
	}

	public void setIdCliente(int idCliente) {
		IdCliente = idCliente;
	}

	public double getCosto() {
		return costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	public void setIdPrenotazione(int idPrenotazione) {
		this.idPrenotazione = idPrenotazione;
	}
	
	public int getMaxId()
	{
		return PrenotazioneDao.getInstance().prenotazioneMaxId();
	}

	public String toString()
	{
		cliente = ClienteBusiness.getInstance().trovaCliente(IdCliente);
		int annoInizio = dataInizio.get(Calendar.YEAR);
		int meseInizio = dataInizio.get(Calendar.MONTH)+1;
		int giornoInizio = dataInizio.get(Calendar.DATE);
		
		int annoFine = dataFine.get(Calendar.YEAR);
		int meseFine = dataFine.get(Calendar.MONTH)+1;
		int giornoFine = dataFine.get(Calendar.DATE);
		
		String conferma;
		if(confermato)
			conferma = "si";
		else
			conferma ="no";
		
		
		String prenotazione ="Pren. num. :"+this.getIdPrenotazione()+
				"   Cliente "+this.IdCliente+":"+this.cliente.getCognome()+" "+this.cliente.getNome()+"  Data Inizio :"+giornoInizio+"-"+
						meseInizio+"-"+annoInizio+"  Data Fine :"+giornoFine+"-"+
								meseFine+"-"+annoFine+"  Codice Cabina:"+this.getCabina()+"  Acqua Corrente :"+this.getAcquaCorrente()+
				"  Elettricita :"+this.getElettricità()+"  Servizio Asciugamani :"+this.getAsciugamani()+"   Costo totale : euro "+this.getCosto()+
				"  Prenotazione confermata :"+conferma ;
		
		return(prenotazione);
	
	
   }
	
	public String stampa()
	{
		//cliente = ClienteBusiness.getInstance().trovaCliente(IdCliente);
		int annoInizio = dataInizio.get(Calendar.YEAR);
		int meseInizio = dataInizio.get(Calendar.MONTH)+1;
		int giornoInizio = dataInizio.get(Calendar.DATE);
		
		int annoFine = dataFine.get(Calendar.YEAR);
		int meseFine = dataFine.get(Calendar.MONTH)+1;
		int giornoFine = dataFine.get(Calendar.DATE);
		
		String conferma;
		if(confermato)
			conferma = "si";
		else
			conferma ="no";	
		
		String prenotazione ="Pren. num. :"+this.getIdPrenotazione()+
				"   IdCliente :"+this.IdCliente+"  Data Inizio :"+giornoInizio+"-"+
						meseInizio+"-"+annoInizio+"  Data Fine :"+giornoFine+"-"+
								meseFine+"-"+annoFine+"  Codice Cabina:"+this.getCabina()+"  Acqua Corrente :"+this.getAcquaCorrente()+
				"  Elettricita :"+this.getElettricità()+"  Servizio Asciugamani :"+this.getAsciugamani()+
				"   Costo totale : euro "+this.getCosto()+"  Confermata :"+conferma ;
		
		return(prenotazione);
	
	
   }
	
	public Prenotazione recupera()
	{
		return(PrenotazioneDao.getInstance().getPrenotazione(this));
	}
	
	public boolean registra()
	{
		
		return(PrenotazioneDao.getInstance().inserisciPrenotazione(this));
	}
	
	public boolean cancella(int idPrenotazione)
	{
		return PrenotazioneDao.getInstance().settaPrenotata(idPrenotazione);
	}
}
